<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KCILITF" failures="1" tests="4" name="Surefire test" time="34.038" errors="0" timestamp="2023-11-26T11:14:23 AST">
  <testcase classname="com.qacart.todo.testcases.SignupTest" name="checkSignUpFunctionality" time="9.206"/>
  <testcase classname="com.qacart.todo.testcases.SignupTest" name="checkfunctionalityOfLogin" time="5.035"/>
  <testcase classname="com.qacart.todo.testcases.TodoTest" name="checkFunctionOfDeleteTask" time="17.822"/>
  <testcase classname="com.qacart.todo.testcases.TodoTest" name="checkFunctionalityOfAddTask" time="8.491">
    <failure type="java.lang.AssertionError" message="expected [New Task Today] but found [My first task]">
      <![CDATA[java.lang.AssertionError: expected [New Task Today] but found [My first task]
at com.qacart.todo.testcases.TodoTest.checkFunctionalityOfAddTask(TodoTest.java:44)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- checkFunctionalityOfAddTask -->
</testsuite> <!-- Surefire test -->
